[workspace]
resolver = "2"
members = [
    "icon-engine",
    "icon-cli",
]

[workspace.dependencies]
anyhow = "1.0"
thiserror = "1.0"
svg = "0.18"
log = "0.4"
env_logger = "0.10"
rayon = "1.8"
clap = { version = "4.4", features = ["derive"] }
